package view.orderView;

import controller.DishController;
import controller.OrderingController;
import controller.OrdersAccountController;
import java.sql.Date;
import javax.swing.JOptionPane;

public final class OrderFrame extends javax.swing.JInternalFrame {

    private static int currentUserID;
    private static OrderFrame orderFrame;
    private final OrderingController mealsOrderController;
    private final OrdersAccountController ordersAccountController;
    private final DishController dishController;

    private OrderFrame(int currentUserID) {
        initComponents();

        mealsOrderController = new OrderingController();
        ordersAccountController = new OrdersAccountController();
        dishController = new DishController();

        OrderFrame.currentUserID = currentUserID;
        updateTableOrderings();
        updateTableOrdersAccount();
    }

    public static OrderFrame getOrderFrame(int currentUserID) {
        if (orderFrame != null) {
            orderFrame.dispose();
        }
        else {
            orderFrame = new OrderFrame(currentUserID);
        }
        return orderFrame;
    }

    public void updateTableOrderings() {
        java.awt.EventQueue.invokeLater(() -> {
            jTable1.setModel(new OrderingTableModel(mealsOrderController));
        });
    }

    public void updateTableOrdersAccount() {
        java.awt.EventQueue.invokeLater(() -> {
            jTable2.setModel(new OrdersAccountTableModel(ordersAccountController, dishController));
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablesPanel = new javax.swing.JPanel();
        lTablePanel = new javax.swing.JPanel();
        lButtonsPanel = new javax.swing.JPanel();
        addMealsOrder = new javax.swing.JButton();
        removeOrdering = new javax.swing.JButton();
        updateTable = new javax.swing.JButton();
        lScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rTablePanel = new javax.swing.JPanel();
        rButtonsPanel = new javax.swing.JPanel();
        removeordresaccount = new javax.swing.JButton();
        updateTable2 = new javax.swing.JButton();
        addOrdersAccount = new javax.swing.JButton();
        rScrollPanel = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        idTableField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idOrderField = new javax.swing.JTextField();
        idEmployeeField = new javax.swing.JTextField();
        searchWithFilters = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dateField = new org.jdesktop.swingx.JXDatePicker();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idOrderField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        idMealField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        searchWithFilters1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Замовлення");
        setPreferredSize(new java.awt.Dimension(1361, 650));

        tablesPanel.setLayout(new java.awt.BorderLayout());

        lTablePanel.setOpaque(false);
        lTablePanel.setPreferredSize(new java.awt.Dimension(800, 700));
        lTablePanel.setLayout(new java.awt.BorderLayout());

        lButtonsPanel.setToolTipText("");

        addMealsOrder.setText("Add a new order");
        addMealsOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMealsOrderActionPerformed(evt);
            }
        });

        removeOrdering.setText("Delete the order");
        removeOrdering.setName("deleteEmployee"); // NOI18N
        removeOrdering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeOrderingActionPerformed(evt);
            }
        });

        updateTable.setText("Update the table");
        updateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lButtonsPanelLayout = new javax.swing.GroupLayout(lButtonsPanel);
        lButtonsPanel.setLayout(lButtonsPanelLayout);
        lButtonsPanelLayout.setHorizontalGroup(
            lButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lButtonsPanelLayout.createSequentialGroup()
                .addComponent(addMealsOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeOrdering, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(updateTable)
                .addContainerGap(657, Short.MAX_VALUE))
        );
        lButtonsPanelLayout.setVerticalGroup(
            lButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMealsOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeOrdering, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateTable, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        lButtonsPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addMealsOrder, removeOrdering, updateTable});

        lTablePanel.add(lButtonsPanel, java.awt.BorderLayout.SOUTH);

        lScrollPane1.setPreferredSize(new java.awt.Dimension(453, 603));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setMaximumSize(new java.awt.Dimension(9000, 9000));
        jTable1.setPreferredSize(new java.awt.Dimension(600, 100));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        lTablePanel.add(lScrollPane1, java.awt.BorderLayout.CENTER);

        tablesPanel.add(lTablePanel, java.awt.BorderLayout.CENTER);

        rTablePanel.setPreferredSize(new java.awt.Dimension(500, 64));
        rTablePanel.setLayout(new java.awt.BorderLayout());

        rButtonsPanel.setPreferredSize(new java.awt.Dimension(977, 100));

        removeordresaccount.setText("Delete the dish");
        removeordresaccount.setName("deleteEmployee"); // NOI18N
        removeordresaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeordresaccountActionPerformed(evt);
            }
        });

        updateTable2.setText("Update the table");
        updateTable2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTable2ActionPerformed(evt);
            }
        });

        addOrdersAccount.setText("Add a new dish");
        addOrdersAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrdersAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rButtonsPanelLayout = new javax.swing.GroupLayout(rButtonsPanel);
        rButtonsPanel.setLayout(rButtonsPanelLayout);
        rButtonsPanelLayout.setHorizontalGroup(
            rButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rButtonsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addOrdersAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeordresaccount)
                .addGap(30, 30, 30)
                .addComponent(updateTable2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        rButtonsPanelLayout.setVerticalGroup(
            rButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(rButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateTable2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(removeordresaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addOrdersAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        rTablePanel.add(rButtonsPanel, java.awt.BorderLayout.SOUTH);

        rScrollPanel.setPreferredSize(new java.awt.Dimension(300, 403));

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable2.setPreferredSize(new java.awt.Dimension(600, 100));
        jTable2.setRequestFocusEnabled(false);
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        rScrollPanel.setViewportView(jTable2);

        rTablePanel.add(rScrollPanel, java.awt.BorderLayout.CENTER);

        tablesPanel.add(rTablePanel, java.awt.BorderLayout.EAST);

        getContentPane().add(tablesPanel, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(150, 421));

        jLabel11.setText("Телефон");

        jLabel4.setText("Employee ID");

        jLabel3.setText("Table ID");

        jLabel2.setText("Order ID");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Orders Filters");

        searchWithFilters.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        searchWithFilters.setText("Apply");
        searchWithFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchWithFiltersActionPerformed(evt);
            }
        });

        jLabel5.setText("Date");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(idOrderField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(idEmployeeField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(idTableField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchWithFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idOrderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTableField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idEmployeeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(searchWithFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel4.setMinimumSize(new java.awt.Dimension(300, 100));
        jPanel4.setName(""); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 590));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Dishes Filters");

        jLabel7.setText("Order ID");

        jLabel8.setText("Dish ID");

        jLabel9.setText("Amount");

        searchWithFilters1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        searchWithFilters1.setText("Apply");
        searchWithFilters1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchWithFilters1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchWithFilters1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(idMealField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(idOrderField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(idOrderField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idMealField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchWithFilters1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(356, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateTable2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTable2ActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            updateTableOrdersAccount();
        });
    }//GEN-LAST:event_updateTable2ActionPerformed

    private void removeordresaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeordresaccountActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            if (jTable2.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(null, "Please choose a record", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                int orderID = Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
                int dishID = dishController.getDishIDByName(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());
                if (ordersAccountController.deleteOrdersaccount(orderID, dishID) == false) {
                    JOptionPane.showMessageDialog(null, "Error while deleting the record", "Error", JOptionPane.ERROR_MESSAGE);
                }
                updateTableOrdersAccount();
            }
        });
    }//GEN-LAST:event_removeordresaccountActionPerformed

    private void addOrderingActionPerformed(java.awt.event.ActionEvent evt) {                                            
        java.awt.EventQueue.invokeLater(() -> {
            try {
                AddOrdersAccount addOrdersAccount = AddOrdersAccount.getAddOrdersAccount(ordersAccountController);
                orderFrame.getParent().add(addOrdersAccount);
                addOrdersAccount.setLocation(orderFrame.getParent().getLocation().x + 320, orderFrame.getParent().getLocation().y + 120);
                addOrdersAccount.setVisible(true);
                addOrdersAccount.setClosable(true);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error while adding a record \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
    }                                           

    private void updateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTableActionPerformed
        java.awt.EventQueue.invokeLater(this::updateTableOrderings);
    }//GEN-LAST:event_updateTableActionPerformed

    private void searchWithFilters1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchWithFilters1ActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            int orderID = -1;
            int mealID = -1;
            int amount = -1;
            
            if (!idOrderField1.getText().equals("")) {
                orderID = Integer.parseInt(idOrderField1.getText());
            }
            
            if (!idMealField.getText().equals("")) {
                mealID = Integer.parseInt(idMealField.getText());
            }
            
            if (!amountField.getText().equals("")) {
                amount = Integer.parseInt(amountField.getText());
            }
            
            jTable2.setModel(new OrdersAccountTableModel(ordersAccountController, dishController, orderID, mealID, amount));
            jTable2.updateUI();
        });
    }//GEN-LAST:event_searchWithFilters1ActionPerformed

    private void searchWithFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchWithFiltersActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            int orderID = -1;
            int tableID = -1;
            int employeeID = -1;
            Date date = null;
            
            if (!idOrderField.getText().equals("")) {
                orderID = Integer.parseInt(idOrderField.getText());
            }
            
            if (!idTableField.getText().equals("")) {
                tableID = Integer.parseInt(idTableField.getText());
            }
            
            if (!idEmployeeField.getText().equals("")) {
                employeeID = Integer.parseInt(idEmployeeField.getText());
            }
            
            if (dateField.getDate() != null) {
                date = new Date(dateField.getDate().getTime());
                
            }
            
            jTable1.setModel(new OrderingTableModel(mealsOrderController, orderID, tableID, employeeID, date));
        });
    }//GEN-LAST:event_searchWithFiltersActionPerformed

    private void addOrdersAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrdersAccountActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            try {
                AddOrdersAccount addOrdersAccount = AddOrdersAccount.getAddOrdersAccount(ordersAccountController);
                orderFrame.getParent().add(addOrdersAccount);
                addOrdersAccount.setLocation(orderFrame.getParent().getLocation().x + 320, orderFrame.getParent().getLocation().y + 120);
                addOrdersAccount.setVisible(true);
                addOrdersAccount.setClosable(true);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error while adding a record \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
    }//GEN-LAST:event_addOrdersAccountActionPerformed

    private void addMealsOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMealsOrderActionPerformed
         java.awt.EventQueue.invokeLater(() -> {
            try {
                AddOrdering addOrdering = AddOrdering.getAddOrdering(mealsOrderController, currentUserID);
                orderFrame.getParent().add(addOrdering);
                addOrdering.setLocation(orderFrame.getParent().getLocation().x + 320, orderFrame.getParent().getLocation().y + 120);
                addOrdering.setVisible(true);
                addOrdering.setClosable(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error while adding the record \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
        
    }//GEN-LAST:event_addMealsOrderActionPerformed

    private void removeOrderingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeOrderingActionPerformed
        
        java.awt.EventQueue.invokeLater(() -> {
            if (jTable1.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(null, "Please, choose a record", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                int orderID = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                if (mealsOrderController.deleteOrdering(orderID) == false) {
                    JOptionPane.showMessageDialog(null, "Error while deleting the record", "Error", JOptionPane.ERROR_MESSAGE);
                }
                updateTableOrderings();
                jTable1.updateUI();
            }
        });
    }//GEN-LAST:event_removeOrderingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMealsOrder;
    private javax.swing.JButton addOrdersAccount;
    private javax.swing.JTextField amountField;
    private org.jdesktop.swingx.JXDatePicker dateField;
    private javax.swing.JTextField idEmployeeField;
    private javax.swing.JTextField idMealField;
    private javax.swing.JTextField idOrderField;
    private javax.swing.JTextField idOrderField1;
    private javax.swing.JTextField idTableField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel lButtonsPanel;
    private javax.swing.JScrollPane lScrollPane1;
    private javax.swing.JPanel lTablePanel;
    private javax.swing.JPanel rButtonsPanel;
    private javax.swing.JScrollPane rScrollPanel;
    private javax.swing.JPanel rTablePanel;
    private javax.swing.JButton removeOrdering;
    private javax.swing.JButton removeordresaccount;
    private javax.swing.JButton searchWithFilters;
    private javax.swing.JButton searchWithFilters1;
    private javax.swing.JPanel tablesPanel;
    private javax.swing.JButton updateTable;
    private javax.swing.JButton updateTable2;
    // End of variables declaration//GEN-END:variables
}
